{
  try {
    throw new Win32Exception(W32Errors.S_OK);
  }
 catch (  Win32Exception e) {
    assertLastErrorValue(e,W32Errors.ERROR_SUCCESS,"The operation completed successfully.");
  }
}
